#!/bin/bash
# register-device.sh
#
# Sets up a physical Raspberry Pi speaker: creates its AWS IoT identity
# (Thing + certificate), installs the player software, copies the certs +
# subscriber onto the Pi, and enables an auto-start service.
#
# NOTE: register the speaker in the WEBSITE first (Speakers tab -> "Generate
# speaker ID"). That creates the device's app record and gives you the ID to
# pass below. This script no longer touches the app database, so it needs no
# login / admin token — it only uses your AWS credentials and SSH.
#
# Usage: ./register-device.sh <DEVICE_CODE> <pi-hostname-or-ip> [ssh-user]
# Example: ./register-device.sh PI-00002 pi-002.local admin
#
# If ssh-user is omitted, defaults to "admin".
#
# Requires:
#   - AWS CLI configured with IoT permissions (create-thing,
#     create-keys-and-certificate, attach-policy, attach-thing-principal)
#   - jq installed locally
#   - SSH access to the target Pi already working (Wi-Fi + SSH configured via
#     Raspberry Pi Imager). Tip: run `ssh-copy-id <user>@<pi>` once so the SSH
#     steps below don't keep asking for the Pi's password.
#   - pi_subscriber.py present at PI_SUBSCRIBER_SOURCE (edit path below if needed)

set -e

DEVICE_CODE=$1
PI_HOST=$2
SSH_USER=${3:-admin}

POLICY_NAME="nicu-device-policy"
CERTS_ROOT="./certs"
PI_SUBSCRIBER_SOURCE="../pi/pi_subscriber.py"  # adjust if your layout differs

if [ -z "$DEVICE_CODE" ] || [ -z "$PI_HOST" ]; then
    echo "Usage: ./register-device.sh <DEVICE_CODE> <pi-hostname-or-ip> [ssh-user]"
    echo "Example: ./register-device.sh PI-00002 pi-002.local admin"
    echo ""
    echo "Get the DEVICE_CODE from the website first: Speakers tab -> Generate speaker ID."
    exit 1
fi

if [ ! -f "$PI_SUBSCRIBER_SOURCE" ]; then
    echo "Error: pi_subscriber.py not found at $PI_SUBSCRIBER_SOURCE"
    echo "Edit PI_SUBSCRIBER_SOURCE at the top of this script to point at the real file."
    exit 1
fi

DEVICE_CERT_DIR="$CERTS_ROOT/$DEVICE_CODE"
mkdir -p "$DEVICE_CERT_DIR"

echo "==> [1/4] Creating $DEVICE_CODE's identity in AWS IoT Core..."

# Create the Thing. Tolerate "already exists" so the script is safe to re-run.
if aws iot create-thing --thing-name "$DEVICE_CODE" > /dev/null 2>&1; then
    echo "    Thing created."
else
    echo "    Thing already exists — reusing."
fi

# Only mint a NEW certificate if we don't already have one locally for this device.
# Re-runs then reuse the existing cert instead of leaving orphaned certs in AWS.
if [ -f "$DEVICE_CERT_DIR/${DEVICE_CODE}_certificate.crt" ] && [ -f "$DEVICE_CERT_DIR/cert-info.json" ]; then
    CERT_ARN=$(jq -r '.certificateArn' "$DEVICE_CERT_DIR/cert-info.json")
    echo "    Certificate already present — reusing."
else
    aws iot create-keys-and-certificate \
        --set-as-active \
        --certificate-pem-outfile "$DEVICE_CERT_DIR/${DEVICE_CODE}_certificate.crt" \
        --public-key-outfile "$DEVICE_CERT_DIR/${DEVICE_CODE}_public.key" \
        --private-key-outfile "$DEVICE_CERT_DIR/${DEVICE_CODE}_private.key" \
        > "$DEVICE_CERT_DIR/cert-info.json"

    CERT_ARN=$(jq -r '.certificateArn' "$DEVICE_CERT_DIR/cert-info.json")
    echo "    Certificate generated."

    aws iot attach-policy --policy-name "$POLICY_NAME" --target "$CERT_ARN"
    echo "    Policy attached."

    aws iot attach-thing-principal --thing-name "$DEVICE_CODE" --principal "$CERT_ARN"
    echo "    Certificate attached to Thing."
fi

if [ ! -f "$CERTS_ROOT/AmazonRootCA1.pem" ]; then
    curl -s -o "$CERTS_ROOT/AmazonRootCA1.pem" https://www.amazontrust.com/repository/AmazonRootCA1.pem
fi
cp "$CERTS_ROOT/AmazonRootCA1.pem" "$DEVICE_CERT_DIR/AmazonRootCA1.pem"
echo "    Amazon Root CA ready."

# The Pi reads its own name from this small config file.
cat > "$DEVICE_CERT_DIR/device_config.py" <<EOF
# device_config.py — auto-generated by register-device.sh
DEVICE_CODE = "$DEVICE_CODE"
EOF

echo "==> [2/4] Copying everything onto the Pi at $PI_HOST..."
echo "    (Tip: run 'ssh-copy-id $SSH_USER@$PI_HOST' once to stop the password prompts.)"

# Build the systemd USER unit locally so it can be copied together with the rest.
# It's a *user* service (installed under ~/.config/systemd/user) so it runs inside
# the user's session and can reach the Pi's audio (PipeWire) — a system service
# can't, which makes mpg123 fail with no sound. No `User=` line (it runs as the
# user), and no network-online dependency (Restart=always retries until the
# network + AWS are reachable).
cat > "$DEVICE_CERT_DIR/pi-subscriber.service" <<EOF
[Unit]
Description=NICU speaker subscriber

[Service]
ExecStart=/usr/bin/python3 /home/$SSH_USER/pi_subscriber.py
WorkingDirectory=/home/$SSH_USER
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF

# One SSH: install the Python libraries (no sudo) and make the certs folder.
# --break-system-packages is required on newer Raspberry Pi OS.
ssh "$SSH_USER@$PI_HOST" "python3 -m pip install paho-mqtt requests --break-system-packages && mkdir -p ~/certs"
echo "    Python libraries installed; ~/certs ready."

# One SCP for the certificate files, one for the home-dir files (config, player, service).
scp -q "$DEVICE_CERT_DIR"/*.crt "$DEVICE_CERT_DIR"/*.key "$DEVICE_CERT_DIR/AmazonRootCA1.pem" "$SSH_USER@$PI_HOST:~/certs/"
scp -q "$DEVICE_CERT_DIR/device_config.py" "$PI_SUBSCRIBER_SOURCE" "$DEVICE_CERT_DIR/pi-subscriber.service" "$SSH_USER@$PI_HOST:~/"
echo "    Certificates, player, config, and service unit copied."

echo "==> [3/4] Installing the audio player + starting the service (asks for the Pi's password once)..."

# One interactive session (`ssh -t` so sudo can prompt, once):
#   - install mpg123 (system package, needs sudo)
#   - enable lingering so the user's systemd + audio start at boot without a login
#   - install + start the subscriber as a USER service (has audio access)
# $SSH_USER expands locally (for enable-linger); \$(id -u) expands on the Pi.
# Note: `enable` sets it to start on boot; `restart` (not `enable --now`) forces
# it to load the freshly-copied config + certificate even if it's already running
# from a previous run — otherwise a re-run keeps using the OLD device code/cert.
ssh -t "$SSH_USER@$PI_HOST" "sudo apt-get update -qq && sudo apt-get install -y -qq mpg123 && sudo loginctl enable-linger $SSH_USER && sleep 1 && export XDG_RUNTIME_DIR=/run/user/\$(id -u) && mkdir -p ~/.config/systemd/user && mv ~/pi-subscriber.service ~/.config/systemd/user/pi-subscriber.service && systemctl --user daemon-reload && systemctl --user enable pi-subscriber.service && systemctl --user restart pi-subscriber.service"
echo "    mpg123 installed; user service enabled and started (auto-starts on boot, restarts on crash)."

echo "==> [4/4] Done."
echo ""
echo "$DEVICE_CODE is set up. It should now show Online in the Speakers tab."
echo "The subscriber runs as a user service — it comes back on its own after a reboot."
echo "Check it any time (SSH in first, then run):"
echo "  ssh $SSH_USER@$PI_HOST"
echo "  systemctl --user status pi-subscriber.service"
echo ""
echo "Last step: assign it to a baby in the website (Speakers tab -> Assign)."
